services:
  # Backend API service
  - type: web
    name: productspecmaster-clean
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: product-spec-master-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false
      - key: REPLIT_APP_ID
        sync: false
      - key: REPLIT_CLIENT_ID
        sync: false
      - key: REPLIT_CLIENT_SECRET
        sync: false
      - key: REPLIT_REDIRECT_URI
        sync: false

databases:
  - name: product-spec-master-db
    databaseName: product_spec_master
    user: product_spec_master_user
    plan: free
